spring:
  profiles:
    active:
      - cat
      - EN
      - prod
guru:
  username: YmlUserName
  password: YmlPassword
  jdbcUrl: YmlSomeUrl

---
spring:
  profiles: prod
guru:
  username: YmlProdUserName
  password: YmlProdPassword
  jdbcUrl: YmlProdSomeUrl
